source "http://rubygems.org"

group :development do
  gem "rspec", "~> 3.2"
  gem "rdoc", "~> 3.12"
  gem "bundler", "~> 1.0"
  gem "jeweler", "~> 2.0.1"
  gem "simplecov", ">= 0"
  gem "pry"
end
gem 'retrospec',  "~> 0.4.0"
